### ISSUE TITLE
grep error during install

### ISSUE THREAD

**Issue by joehillen** [danhper/fish-ssh-agent#1]
```
Cloning into '/home/joe/.config/fish/fundle/tuvistavie/fish-ssh-agent'...
remote: Counting objects: 6, done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 6
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

I suspect the issue is [here](https://github.com/tuvistavie/fish-ssh-agent/blob/master/init.fish#L9) when `$SSH_AGENT_PID` is void.

**Comment by danhper** [comment]
Hi,
I see, I suppose it depends on the implementation of grep, as it seems to work for me even when `SSH_AGENT_PID` is not defined.
I updated the package so that we do not grep if `SSH_AGENT_PID` is not defined.
I think that should solve the issue, but please reopen if it does not.
