### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by cfjedimaster** [danhper/fish-ssh-agent#9]
When installing, I got a large set of errors that all seemed to be repeats of:

    Unsupported use of '='.

This is with Ubuntu on Windows 10.

**Comment by cfjedimaster** [comment]
Sorry - this was an older version of Fish issue.

**Comment by deltaidea** [comment]
For other people coming from Google:

```
rm ~/.ssh/environment
```

This file is used by `fish-ssh-agent`. Most likely it's been generated in an incompatible fashion by an older version or another utility.
